### ISSUE TITLE
Error in code

### ISSUE THREAD

**Issue by chupocro** [martinhansdk/DS1621-temperature-probe-library-for-Arduino#3]
Hi,

there is an error in **DS1621::getHrTemp()**, instead of:

`tHR = (25 - tHR * 100) + ((slope - cRem) * 100 / slope);`

it should be:

`tHR = (-25 - tHR * 100) + ((slope - cRem) * 100 / slope);`

Your code introduces an error of +0.5°C whenever `tVal <= -1`. I made a temperature logger with ESP8266 using your library and there was the disruption (+0.5° jump) on the graph everytime the temperature dropped below -0.5° (that is when `tVal` becomes -1).

BTW, to make the library work with ESP8266 the line:

`tC = 0xFF00 | tVal;`

should be changed into:

`tC = 0xFFFFFF00 | tVal;`

To avoid returning +65535 instead of -1, +65534 instead of -2 etc. That is because ESP is 32 bit --> `sizeof(int)` is 4 bytes.

**Comment by martinhansdk** [comment]
Thanks for the contribution. I have added your fixes.

**Comment by chupocro** [comment]
You are welcome! This was BTW my very first github contribution :-)
